Implements back the port based SSL certificate fetching.
space-wizards/ManagedHttpListener pull request #7
Opened 2024-08-08 22:00 UTC by GitHubProUser67

Implements back the port based SSL certificate fetching.

This modernize the Mono code base to allow booth, a in-memory cache and that same file-based cache if the in-memory cache doesn't contain the entry.

This makes the previous SetCertificate constructor obsolete, but for good, since we can now set a different certificate per ports.

This is not SNI level, but it's still leagues beyond the actual .NET implementation (the MYSTICAL null stubbed return value with the TODO ^^).

2024-08-11 17:52 UTC, PJB3005 commented
Do you have an actual use case for this? The reason the mono code even *has* that port-based logic is dated and ancient, I don't see any reason to keep it as functionality here.

2024-08-11 18:43 UTC, GitHubProUser67 commented
I do have an use case if I host various CN names on various ports without having to rely on SAN attributes.

2024-08-11 21:43 UTC, PJB3005 commented
> I do have an use case if I host various CN names on various ports without having to rely on SAN attributes.

Do *you* have an actual use case for this? Sure obviously this would allow you to have separate TLS certs served per port but *what* use case could that possibly have in 2024 to warrant implementing?

I would rather have a more flexible API that also incorporated SNI support or similar via e.g. a callback. Then you can just add the destination socket port in one of the parameters the selection logic and users that *really* need this can take it from there.

2024-08-12 08:11 UTC, GitHubProUser67 commented
So, the full story is I did this mostly for "completeness" more than anything, I do plan under the hood onto making a SNI api based on the work I did on my server suit (a certificate signing chain).

Long story short, my plan is making a check for if the certificate that is set is a Root CA or a chain signed cert, if Root CA enable the SNI signing system.

I do have locally a system like this in place, but for some reasons it not work as intended just yet (the reason it's not there yet).

2024-08-12 16:08 UTC, GitHubProUser67 commented
The SNI support has finally be added in the repository @PJB3005 !

The way it works is simply by inserting the Root CA Certificate instead of the classic chain signed certificate (via the same constructor), and HTTPListener will sign itself intermediate certificates that are instanced per-session.

Simple and powerfull ^^.

2024-08-13 09:47 UTC, PJB3005 commented
> and HTTPListener will sign itself intermediate certificates that are instanced per-session.

Uh, what? Does that actually work? You can't self-sign certificates. And you can't get a root CA cert from anywhere? And isn't signing way too expensive to do for every TLS connection?

2024-08-13 12:47 UTC, GitHubProUser67 commented
I can confirm it works just fine, the root CA will need to be obtained from an outside source (I can make a generator for it too if needed), then this CA cert will be used to sign all the certificates that are generated on the fly.

They are all valid for a period of 7 days to avoids making too much of them (this can be extended).

2025-03-05 21:25 UTC, PJB3005 requested changes

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +        private static readonly string[] tlds = {
This is an extremely outdated list of TLDs. You cannot hardcode something like this.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +                $" O=\"SpaceWizards Corp\", L=New York, S=Northeastern United, C=US", rsa, certHashAlgorithm, RSASignaturePadding.Pkcs1);
This organization does not exist and it should not be hardcoded in the library.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +            sanBuilder.AddEmailAddress("SpaceWizards@gmail.com");
This email address does not exist and it should not be hardcoded in the library.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +            new Random().NextBytes(certSerialNumber);
This rando isn't cryptographically secure.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +        }
This random isn't cryptographically secure.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +        }
This is not a correct way to check this, nor should this library care.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +        // Workaround for SHA1 and MD5 ban in .NET 4.7.2 and .NET Core.
We are not implementing workarounds to security issues like this.

2025-03-05 21:25 UTC, PJB3005 commented on src/System/Net/CertificateHelper.cs
> +        }
.NET has built-in libraries for this.

2025-03-05 21:26 UTC, PJB3005 commented
I am closing this PR. Based on the code I have skimmed over so far it is clear to me that:

1. This code has absolutely no place, whatsoever, in being in a library like this.
2. I hate to say this, but you likely do not know what you are doing when it comes to TLS certificates.

If you want to have a way to specify custom certificates dynamically like this, a PR that adds a simple callback so that library consumers can pass their own cert is all that should be necessary. You can implement whatever... this is.. on top of that.

2025-03-05 21:26 UTC, closed without merging

2025-03-06 06:28 UTC, GitHubProUser67 commented
Okay, most of these are valid points I admit.

However, if I am being completely honest, I do not understand, nor like, the 2. sentence there, I would like some examples and proof as to where I didn't understand how TLS worked.

Some code might not be the best way to put it, but, as far as I know, the certs "works" so does TLS, it is simply skimming over some security, which is a valid point for it not being merged.

2025-03-06 23:39 UTC, PJB3005 commented
> However, if I am being completely honest, I do not understand, nor like, the 2. sentence there, I would like some examples and proof as to where I didn't understand how TLS worked.

You are self-signing certificates to implement SNI, directly for any domain clients ask for. This is not something you can do in the real world unless you have your own CA certs preinstalled on client machines. Even if you did have that, it would be grossly irresponsible from a security perspective to have your web server self signing certificates right then and there for anything other than dev environment testing.

2025-03-06 23:51 UTC, metalgearsloth commented
> as far as I know, the certs "works" so does TLS, it is simply skimming over some security,

Isn't security the whole point of the exercise?

2025-03-07 02:02 UTC, GitHubProUser67 commented
I better understand the point now, the security argument is valid, I did use this system so old systems where SSL is a requirement could work.

On my fork I re-did that a bit, to also support chain signed certificate from an other CA (by loading the file directly if it exists) with a fallback to that system if not found.

But after all, this is quite use-case specific, so maybe it is best suited for the fork only.